import 'package:procdev/model/db_constant.dart'; // Import your constants

class Product {
  final int? id; // Nullable because it's generated by the DB on insert
  final String name;
  final double price; // Kept as String to match your initial data
  final String image;
  final String category;
  final String? description; // Nullable as per your data

  const Product({
    this.id,
    required this.name,
    required this.price,
    required this.image,
    required this.category,
    this.description,
  });

  factory Product.fromMap(Map<String, dynamic> map) {
    return Product(
      id: map[DBConstant.colId] as int?,
      name: map[DBConstant.colName] as String,
      price: map[DBConstant.colPrice] as double,
      image: map[DBConstant.colImage] as String,
      category: map[DBConstant.colCategory] as String,
      description: map[DBConstant.colDescription] as String?,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (id != null) DBConstant.colId: id,
      DBConstant.colName: name,
      DBConstant.colPrice: price,
      DBConstant.colImage: image,
      DBConstant.colCategory: category,
      DBConstant.colDescription: description,
    };
  }
}
