import 'package:flutter/foundation.dart';    
import 'package:firebase_core/firebase_core.dart';
// import 'package:flutter/foundation.dart';
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
    // show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1UQpj1x7zc6Uu8rqOUGLFkMJxATI_Iek',
    appId: '1:1059431764007:web:9692929cd3d59789e5be02',
    messagingSenderId: '1059431764007',
    projectId: 'butproject-5ff43',
    authDomain: 'butproject-5ff43.firebaseapp.com',
    storageBucket: 'butproject-5ff43.firebasestorage.app',
    measurementId: 'G-0CYY50T1TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQwG0FvIdFH3YcN97yZZ13J73DYh0kt0',
    appId: '1:1059431764007:android:c7fb5ea4b251a6f0e5be02',
    messagingSenderId: '1059431764007',
    projectId: 'butproject-5ff43',
    storageBucket: 'butproject-5ff43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWQZslXIf34AR_1W86s2BZ-o7D0pGAos',
    appId: '1:1059431764007:ios:2a440c8570598b0ce5be02',
    messagingSenderId: '1059431764007',
    projectId: 'butproject-5ff43',
    storageBucket: 'butproject-5ff43.firebasestorage.app',
    iosBundleId: 'com.example.procdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWQZslXIf34AR_1W86s2BZ-o7D0pGAos',
    appId: '1:1059431764007:ios:2a440c8570598b0ce5be02',
    messagingSenderId: '1059431764007',
    projectId: 'butproject-5ff43',
    storageBucket: 'butproject-5ff43.firebasestorage.app',
    iosBundleId: 'com.example.procdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1UQpj1x7zc6Uu8rqOUGLFkMJxATI_Iek',
    appId: '1:1059431764007:web:c619090261a81bafe5be02',
    messagingSenderId: '1059431764007',
    projectId: 'butproject-5ff43',
    authDomain: 'butproject-5ff43.firebaseapp.com',
    storageBucket: 'butproject-5ff43.firebasestorage.app',
    measurementId: 'G-F09ZGDFXZS',
  );
}
